-- =============================================================
-- CineBook Phase 3 - Oracle schema
-- Official Oracle SQL Developer version for CMPG 311.
-- Logical model: 9 tables, aligned to Phase 2.
-- =============================================================

SET DEFINE OFF;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE Payment CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE BookingSeat CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Booking CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ShowSchedule CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Seat CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Screen CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Users CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Theatre CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Movie CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Parent tables

CREATE TABLE Movie (
    Movie_Id          NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    Title             VARCHAR2(150) NOT NULL,
    Genre             VARCHAR2(50)  NOT NULL,
    Duration_Minutes  NUMBER(5)     NOT NULL,
    Age_Rating        VARCHAR2(10)  NOT NULL,
    Description       CLOB,
    Cast_Info         CLOB,
    Poster_Url        VARCHAR2(500),
    CONSTRAINT chk_movie_duration CHECK (Duration_Minutes > 0)
);

CREATE TABLE Theatre (
    Theatre_Id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    Name           VARCHAR2(100) NOT NULL,
    Location       VARCHAR2(200) NOT NULL,
    City           VARCHAR2(100) NOT NULL,
    Total_Screens  NUMBER(5)     DEFAULT 0 NOT NULL,
    CONSTRAINT chk_theatre_total_screens CHECK (Total_Screens >= 0)
);

CREATE TABLE Users (
    User_Id         NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    First_Name      VARCHAR2(50)  NOT NULL,
    Last_Name       VARCHAR2(50)  NOT NULL,
    Email           VARCHAR2(100) NOT NULL,
    Phone_Number    VARCHAR2(20),
    Password_Hash   VARCHAR2(255) NOT NULL,
    Role            VARCHAR2(30) DEFAULT 'Customer' NOT NULL,
    Loyalty_Status  VARCHAR2(20) DEFAULT 'Standard' NOT NULL,
    Created_At      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    Theatre_Id      NUMBER(10),
    CONSTRAINT uq_users_email UNIQUE (Email),
    CONSTRAINT chk_users_role
        CHECK (Role IN ('Customer', 'Administrator', 'Cinema Manager', 'System Administrator')),
    CONSTRAINT chk_users_loyalty
        CHECK (Loyalty_Status IN ('Standard', 'Silver', 'Gold', 'Platinum')),
    CONSTRAINT fk_users_theatre
        FOREIGN KEY (Theatre_Id) REFERENCES Theatre(Theatre_Id)
);

CREATE TABLE Screen (
    Screen_Id      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    Screen_Name    VARCHAR2(50) NOT NULL,
    Total_Seats    NUMBER(5)    NOT NULL,
    Screen_Type    VARCHAR2(20) DEFAULT 'Standard' NOT NULL,
    Theatre_Id     NUMBER(10)   NOT NULL,
    CONSTRAINT chk_screen_total_seats CHECK (Total_Seats >= 0),
    CONSTRAINT chk_screen_type CHECK (Screen_Type IN ('Standard', 'Premium', 'VIP')),
    CONSTRAINT fk_screen_theatre FOREIGN KEY (Theatre_Id) REFERENCES Theatre(Theatre_Id)
);

CREATE TABLE Seat (
    Seat_Id      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    Row_Label    CHAR(1)      NOT NULL,
    Seat_Number  NUMBER(5)    NOT NULL,
    Seat_Type    VARCHAR2(20) DEFAULT 'Standard' NOT NULL,
    Screen_Id    NUMBER(10)   NOT NULL,
    CONSTRAINT uq_seat_position UNIQUE (Screen_Id, Row_Label, Seat_Number),
    CONSTRAINT chk_seat_number CHECK (Seat_Number > 0),
    CONSTRAINT chk_seat_type CHECK (Seat_Type IN ('Standard', 'Premium', 'VIP')),
    CONSTRAINT fk_seat_screen FOREIGN KEY (Screen_Id) REFERENCES Screen(Screen_Id)
);

CREATE TABLE ShowSchedule (
    Show_Id         NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    Show_DateTime   TIMESTAMP    NOT NULL,
    Price_Per_Seat  NUMBER(10,2) NOT NULL,
    Movie_Id        NUMBER(10)   NOT NULL,
    Screen_Id       NUMBER(10)   NOT NULL,
    CONSTRAINT chk_show_price CHECK (Price_Per_Seat >= 0),
    CONSTRAINT uq_show_screen_time UNIQUE (Screen_Id, Show_DateTime),
    CONSTRAINT fk_show_movie FOREIGN KEY (Movie_Id) REFERENCES Movie(Movie_Id),
    CONSTRAINT fk_show_screen FOREIGN KEY (Screen_Id) REFERENCES Screen(Screen_Id)
);

CREATE TABLE Booking (
    Booking_Id    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    Booking_Date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    Status        VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    Total_Amount  NUMBER(10,2) DEFAULT 0 NOT NULL,
    User_Id       NUMBER(10) NOT NULL,
    Show_Id       NUMBER(10) NOT NULL,
    CONSTRAINT chk_booking_status CHECK (Status IN ('pending', 'confirmed', 'cancelled')),
    CONSTRAINT chk_booking_amount CHECK (Total_Amount >= 0),
    CONSTRAINT fk_booking_user FOREIGN KEY (User_Id) REFERENCES Users(User_Id),
    CONSTRAINT fk_booking_show FOREIGN KEY (Show_Id) REFERENCES ShowSchedule(Show_Id)
);

CREATE TABLE BookingSeat (
    BookingSeat_Id  NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    Booking_Id      NUMBER(10) NOT NULL,
    Seat_Id         NUMBER(10) NOT NULL,
    Show_Id         NUMBER(10) NOT NULL,
    CONSTRAINT uq_bookingseat_show_seat UNIQUE (Show_Id, Seat_Id),
    CONSTRAINT fk_bookingseat_booking FOREIGN KEY (Booking_Id) REFERENCES Booking(Booking_Id),
    CONSTRAINT fk_bookingseat_seat FOREIGN KEY (Seat_Id) REFERENCES Seat(Seat_Id),
    CONSTRAINT fk_bookingseat_show FOREIGN KEY (Show_Id) REFERENCES ShowSchedule(Show_Id)
);

CREATE TABLE Payment (
    Payment_Id             NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    Payment_Date           TIMESTAMP,
    Amount                 NUMBER(10,2) NOT NULL,
    Payment_Method         VARCHAR2(20) DEFAULT 'Card' NOT NULL,
    Payment_Status         VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    Transaction_Reference  VARCHAR2(100),
    Booking_Id             NUMBER(10) NOT NULL,
    CONSTRAINT uq_payment_booking UNIQUE (Booking_Id),
    CONSTRAINT chk_payment_amount CHECK (Amount > 0),
    CONSTRAINT chk_payment_method CHECK (Payment_Method IN ('Card', 'EFT', 'Cash')),
    CONSTRAINT chk_payment_status CHECK (Payment_Status IN ('pending', 'successful', 'failed')),
    CONSTRAINT fk_payment_booking FOREIGN KEY (Booking_Id) REFERENCES Booking(Booking_Id)
);

SELECT table_name
FROM user_tables
WHERE table_name IN (
    'USERS', 'MOVIE', 'THEATRE', 'SCREEN', 'SEAT',
    'SHOWSCHEDULE', 'BOOKING', 'BOOKINGSEAT', 'PAYMENT'
)
ORDER BY table_name;
